#!/usr/bin/env bash
# Bash script to display DNS records: record type, IP, subdomains
print_dns_record() {
	if [ -n "$2" ]
	then
		dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$2" '{print "The subdomain " sd " is a " $7 " record and points to " $8}'
	else 
		dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain www is a " $7 " record and points to " $8}'
		dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain lb-01 is a " $7 " record and points to " $8}'
		dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-01 is a " $7 " record and points to " $8}'
		dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-02 is a " $7 " record and points to " $8}'
	fi
}


if [ -z "$1" ]; then
    echo "Error: Missing domain argument"
    exit 1
fi

if [ -z "$2" ]; then
        print_dns_record "$1" "$subdomain"
else
    print_dns_record "$1" "$2"
fi

