#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

if [ "$#" -lt 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
	file_path="$1"
	server_ip="$2"
	username="$3"
	ssh_key_path="$4"
	scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ 
fi
