#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart

