#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart

