#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
