#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html;
    location /redirect_me {
        return 301  https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /usr/share/nginx/html;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
