#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
        index index.html;
        add_header Content-Type text/html;
        echo "Ceci n'est pas une page";
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

sudo service nginx restart
