#!/usr/bin/env bash
# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "s/#error_page 404/error_page 404" /etc/nginx/sites-enabled/default
echo "page not found" | sudo tee /usr/share/nginx/html/404.html
sudo service nginx restart
