#!/usr/bin/env bash
#install nginx
#serve web page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow install 'Nginx HTTP'
sudo mkdir -p /var/www/html/ /var/www/error
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html;
    server_name _;
    add_header X-Served-By \$HOSTNAME;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /usr/share/nginx/html/;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
