#!/usr/bin/env bash
#What if the data center where both your primary and replica database servers
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -cvzf "$(date '+%d-%m-%Y.tar.gz')" backup.sql
