#!/usr/bin/env bash
# Update Nginx configuration to listen on port 80
#sudo apt update
#sudo apt-get -y install curl
sudo rm /etc/nginx/sites-available/*
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sudo rm /etc/nginx/sites-enabled/*~
#sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
