#!/usr/bin/env bash
#read etc pass with shell
while IFS=: read -r USERNAME pass USER GROUP_ID USR_INFO HOME_DIRECTORY COMMAND ; do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER's place is protected by the passcode $pass, more info about the user here: $USR_INFO"
done < /etc/passwd
