#!/usr/bin/env bash
#displays Best School 10 times with while and usie bad and good luck.
hour=0
while [[ $hour -le 12 ]]; do
	echo "Hour: $hour"
	min=1
	while [[ $min -le 59 ]]; do
		echo "$min"
		min=$((min + 1))
	done
	hour=$((hour + 1))
done
