#!/usr/bin/env bash

set -euo pipefail

# Stop Apache2
service apache2 stop || true
pkill apache2 || true

# Configure nginx to run on port 8080
CONFIG_LOCATION='/etc/nginx/sites-available/default'
CONFIG="
server {
	listen 8080 default_server;
	listen [::]:8080 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}
}"
printf "%s" "$CONFIG" > "$CONFIG_LOCATION"

# Ensure nginx.conf permissions are set correctly
chmod u+r /etc/nginx/nginx.conf

# Restart nginx
service nginx restart
